from __future__ import annotations

from typing import Dict, List, Optional


APP_CATALOG: List[Dict[str, str]] = [
    # Instant Lab
    {
        "id": "ai_blog_to_podcast_agent",
        "name": "AI Blog to Podcast Agent",
        "hub": "Instant Lab",
        "path": "instant_lab.ai_blog_to_podcast_agent.app",
        "description": "Convert blog content to podcast format.",
        "status": "ready",
        "badge": "New",
    },
    {
        "id": "ai_breakup_recovery_agent",
        "name": "AI Breakup Recovery Agent",
        "hub": "Instant Lab",
        "path": "instant_lab.ai_breakup_recovery_agent.app",
        "description": "Support for emotional recovery.",
        "status": "ready",
    },
    {
        "id": "ai_data_analysis_agent",
        "name": "AI Data Analysis Agent",
        "hub": "Instant Lab",
        "path": "instant_lab.ai_data_analysis_agent.app",
        "description": "Analyze data with AI.",
        "status": "ready",
    },
    {
        "id": "ai_medical_imaging_agent",
        "name": "AI Medical Imaging Agent",
        "hub": "Instant Lab",
        "path": "instant_lab.ai_medical_imaging_agent.app",
        "description": "Assist with medical imaging analysis.",
        "status": "ready",
    },
    {
        "id": "ai_meme_generator_agent_browseruse",
        "name": "AI Meme Generator Agent (Browser)",
        "hub": "Instant Lab",
        "path": "instant_lab.ai_meme_generator_agent_browseruse.app",
        "description": "Generate memes using browser tools.",
        "status": "ready",
        "badge": "Popular",
    },
    {
        "id": "ai_music_generator_agent",
        "name": "AI Music Generator Agent",
        "hub": "Instant Lab",
        "path": "instant_lab.ai_music_generator_agent.app",
        "description": "Create music with AI.",
        "status": "ready",
    },
    {
        "id": "ai_travel_agent",
        "name": "AI Travel Agent",
        "hub": "Instant Lab",
        "path": "instant_lab.ai_travel_agent.app",
        "description": "Plan trips and generate travel suggestions.",
        "status": "ready",
        "badge": "Fast",
    },
    {
        "id": "gemini_multimodal_agent_demo",
        "name": "Gemini Multimodal Agent Demo",
        "hub": "Instant Lab",
        "path": "instant_lab.gemini_multimodal_agent_demo.app",
        "description": "Demo of multimodal AI capabilities.",
        "status": "ready",
    },
    {
        "id": "mixture_of_agents",
        "name": "Mixture of Agents",
        "hub": "Instant Lab",
        "path": "instant_lab.mixture_of_agents.app",
        "description": "Combine multiple AI agents.",
        "status": "ready",
    },
    {
        "id": "xai_finance_agent",
        "name": "XAI Finance Agent",
        "hub": "Instant Lab",
        "path": "instant_lab.xai_finance_agent.app",
        "description": "Financial analysis and advice.",
        "status": "ready",
    },
    {
        "id": "openai_research_agent",
        "name": "OpenAI Research Agent",
        "hub": "Instant Lab",
        "path": "instant_lab.openai_research_agent.app",
        "description": "Research assistant using OpenAI.",
        "status": "ready",
    },
    {
        "id": "web_scraping_ai_agent",
        "name": "Web Scraping AI Agent",
        "hub": "Instant Lab",
        "path": "instant_lab.web_scraping_ai_agent.app",
        "description": "Scrape and analyze web data.",
        "status": "ready",
    },
    # Revenue Engine
    {
        "id": "ai_consultant_agent",
        "name": "AI Consultant Agent",
        "hub": "Revenue Engine",
        "path": "revenue_engine.ai_consultant_agent.app",
        "description": "Provide consulting advice.",
        "status": "ready",
    },
    {
        "id": "ai_investment_agent",
        "name": "AI Investment Agent",
        "hub": "Revenue Engine",
        "path": "revenue_engine.ai_investment_agent.app",
        "description": "Investment analysis and recommendations.",
        "status": "ready",
    },
    {
        "id": "ai_journalist_agent",
        "name": "AI Journalist Agent",
        "hub": "Revenue Engine",
        "path": "revenue_engine.ai_journalist_agent.app",
        "description": "Generate news and articles.",
        "status": "ready",
    },
    {
        "id": "ai_meeting_agent",
        "name": "AI Meeting Agent",
        "hub": "Revenue Engine",
        "path": "revenue_engine.ai_meeting_agent.app",
        "description": "Assist with meeting management.",
        "status": "ready",
    },
    {
        "id": "ai_fraud_investigation_agent",
        "name": "AI Fraud Investigation Agent",
        "hub": "Revenue Engine",
        "path": "revenue_engine.ai_fraud_investigation_agent.app",
        "description": "Investigate potential fraud.",
        "status": "ready",
    },
    {
        "id": "research_agent_gemini_interaction_api",
        "name": "Research Agent Gemini Interaction API",
        "hub": "Revenue Engine",
        "path": "revenue_engine.research_agent_gemini_interaction_api.app",
        "description": "Research using Gemini API.",
        "status": "ready",
    },
    {
        "id": "product_launch_intelligence_agent",
        "name": "Product Launch Intelligence Agent",
        "hub": "Revenue Engine",
        "path": "revenue_engine.product_launch_intelligence_agent.app",
        "description": "Intelligence for product launches.",
        "status": "ready",
    },
    {
        "id": "ai_sales_intelligence_agent_team",
        "name": "AI Sales Intelligence Agent Team",
        "hub": "Revenue Engine",
        "path": "revenue_engine.ai_sales_intelligence_agent_team.app",
        "description": "Team for sales intelligence.",
        "status": "ready",
    },
    {
        "id": "ai_vc_due_diligence_agent_team",
        "name": "AI VC Due Diligence Agent Team",
        "hub": "Revenue Engine",
        "path": "revenue_engine.ai_vc_due_diligence_agent_team.app",
        "description": "Due diligence for venture capital.",
        "status": "ready",
    },
    {
        "id": "devpulse_ai",
        "name": "DevPulse AI",
        "hub": "Revenue Engine",
        "path": "revenue_engine.devpulse_ai.app",
        "description": "Pulse on development activities.",
        "status": "ready",
    },
    {
        "id": "ai_competitor_intelligence_agent_team",
        "name": "AI Competitor Intelligence Agent Team",
        "hub": "Revenue Engine",
        "path": "revenue_engine.ai_competitor_intelligence_agent_team.app",
        "description": "Competitor analysis team.",
        "status": "ready",
    },
    {
        "id": "ai_finance_agent_team",
        "name": "AI Finance Agent Team",
        "hub": "Revenue Engine",
        "path": "revenue_engine.ai_finance_agent_team.app",
        "description": "Team for financial analysis.",
        "status": "ready",
    },
    {
        "id": "email-drafter",
        "name": "Email Drafter",
        "hub": "Revenue Engine",
        "path": "revenue_engine.email_drafter.app",
        "description": "Draft professional emails.",
        "status": "ready",
    },
    {
        "id": "strategy-advisor",
        "name": "Strategy Advisor",
        "hub": "Revenue Engine",
        "path": "revenue_engine.strategy_advisor.app",
        "description": "Provide strategic advice.",
        "status": "ready",
    },
    {
        "id": "project-planner",
        "name": "Project Planner",
        "hub": "Revenue Engine",
        "path": "revenue_engine.project_planner.app",
        "description": "Plan projects effectively.",
        "status": "ready",
    },
    {
        "id": "meeting-notes",
        "name": "Meeting Notes",
        "hub": "Revenue Engine",
        "path": "revenue_engine.meeting_notes.app",
        "description": "Summarize meeting notes.",
        "status": "ready",
    },
    {
        "id": "decision-helper",
        "name": "Decision Helper",
        "hub": "Revenue Engine",
        "path": "revenue_engine.decision_helper.app",
        "description": "Assist in decision making.",
        "status": "ready",
    },
    {
        "id": "fact-checker",
        "name": "Fact Checker",
        "hub": "Revenue Engine",
        "path": "revenue_engine.fact_checker.app",
        "description": "Verify facts and information.",
        "status": "ready",
    },
    # Creative Studio
    {
        "id": "ai_movie_production_agent",
        "name": "AI Movie Production Agent",
        "hub": "Creative Studio",
        "path": "creative_studio.ai_movie_production_agent.app",
        "description": "Assist in movie production.",
        "status": "ready",
    },
    {
        "id": "ai_home_renovation_agent",
        "name": "AI Home Renovation Agent",
        "hub": "Creative Studio",
        "path": "creative_studio.ai_home_renovation_agent.app",
        "description": "Design home renovations.",
        "status": "ready",
    },
    {
        "id": "ai_news_and_podcast_agents",
        "name": "AI News and Podcast Agents",
        "hub": "Creative Studio",
        "path": "creative_studio.ai_news_and_podcast_agents.app",
        "description": "Generate news and podcasts.",
        "status": "ready",
    },
    {
        "id": "multimodal_design_agent_team",
        "name": "Multimodal Design Agent Team",
        "hub": "Creative Studio",
        "path": "creative_studio.multimodal_design_agent_team.app",
        "description": "Team for multimodal design.",
        "status": "ready",
    },
    {
        "id": "multimodal_uiux_feedback_agent_team",
        "name": "Multimodal UI/UX Feedback Agent Team",
        "hub": "Creative Studio",
        "path": "creative_studio.multimodal_uiux_feedback_agent_team.app",
        "description": "Feedback on UI/UX designs.",
        "status": "ready",
    },
    {
        "id": "content-creator",
        "name": "Content Creator",
        "hub": "Creative Studio",
        "path": "creative_studio.content_creator.app",
        "description": "Create various content types.",
        "status": "ready",
    },
    {
        "id": "editor",
        "name": "Editor",
        "hub": "Creative Studio",
        "path": "creative_studio.editor.app",
        "description": "Edit and refine content.",
        "status": "ready",
    },
    {
        "id": "ux-designer",
        "name": "UX Designer",
        "hub": "Creative Studio",
        "path": "creative_studio.ux_designer.app",
        "description": "Design user experiences.",
        "status": "ready",
    },
    {
        "id": "visualization-expert",
        "name": "Visualization Expert",
        "hub": "Creative Studio",
        "path": "creative_studio.visualization_expert.app",
        "description": "Create data visualizations.",
        "status": "ready",
    },
    # AI Workforce
    {
        "id": "ai_game_design_agent_team",
        "name": "AI Game Design Agent Team",
        "hub": "AI Workforce",
        "path": "ai_workforce.ai_game_design_agent_team.app",
        "description": "Team for game design.",
        "status": "ready",
    },
    {
        "id": "ag2_adaptive_research_team",
        "name": "AG2 Adaptive Research Team",
        "hub": "AI Workforce",
        "path": "ai_workforce.ag2_adaptive_research_team.app",
        "description": "Adaptive research team.",
        "status": "ready",
    },
    {
        "id": "ai_legal_agent_team",
        "name": "AI Legal Agent Team",
        "hub": "AI Workforce",
        "path": "ai_workforce.ai_legal_agent_team.app",
        "description": "Team for legal assistance.",
        "status": "ready",
    },
    {
        "id": "ai_recruitment_agent_team",
        "name": "AI Recruitment Agent Team",
        "hub": "AI Workforce",
        "path": "ai_workforce.ai_recruitment_agent_team.app",
        "description": "Team for recruitment.",
        "status": "ready",
    },
    {
        "id": "ai_real_estate_agent_team",
        "name": "AI Real Estate Agent Team",
        "hub": "AI Workforce",
        "path": "ai_workforce.ai_real_estate_agent_team.app",
        "description": "Team for real estate.",
        "status": "ready",
    },
    {
        "id": "ai_services_agency",
        "name": "AI Services Agency",
        "hub": "AI Workforce",
        "path": "ai_workforce.ai_services_agency.app",
        "description": "Agency for AI services.",
        "status": "ready",
    },
    {
        "id": "ai_teaching_agent_team",
        "name": "AI Teaching Agent Team",
        "hub": "AI Workforce",
        "path": "ai_workforce.ai_teaching_agent_team.app",
        "description": "Team for teaching assistance.",
        "status": "ready",
    },
    {
        "id": "multimodal_coding_agent_team",
        "name": "Multimodal Coding Agent Team",
        "hub": "AI Workforce",
        "path": "ai_workforce.multimodal_coding_agent_team.app",
        "description": "Team for multimodal coding.",
        "status": "ready",
    },
    {
        "id": "ai_travel_planner_agent_team",
        "name": "AI Travel Planner Agent Team",
        "hub": "AI Workforce",
        "path": "ai_workforce.ai_travel_planner_agent_team.app",
        "description": "Team for travel planning.",
        "status": "ready",
    },
    {
        "id": "ai_self_evolving_agent",
        "name": "AI Self-Evolving Agent",
        "hub": "AI Workforce",
        "path": "ai_workforce.ai_self_evolving_agent.app",
        "description": "Self-evolving AI agent.",
        "status": "ready",
    },
    {
        "id": "trust_gated_agent_team",
        "name": "Trust Gated Agent Team",
        "hub": "AI Workforce",
        "path": "ai_workforce.trust_gated_agent_team.app",
        "description": "Team with trust gating.",
        "status": "ready",
    },
    # Voice Command Center
    {
        "id": "ai_audio_tour_agent",
        "name": "AI Audio Tour Agent",
        "hub": "Voice Command Center",
        "path": "voice_command.ai_audio_tour_agent.app",
        "description": "Audio-guided tours.",
        "status": "ready",
    },
    {
        "id": "customer_support_voice_agent",
        "name": "Customer Support Voice Agent",
        "hub": "Voice Command Center",
        "path": "voice_command.customer_support_voice_agent.app",
        "description": "Voice-based customer support.",
        "status": "ready",
    },
    {
        "id": "voice_rag_openaisdk",
        "name": "Voice RAG OpenAI SDK",
        "hub": "Voice Command Center",
        "path": "voice_command.voice_rag_openaisdk.app",
        "description": "Voice retrieval-augmented generation.",
        "status": "ready",
    },
    {
        "id": "jarvis-ai-assistant",
        "name": "Jarvis AI Assistant",
        "hub": "Voice Command Center",
        "path": "voice_command.jarvis_ai_assistant.app",
        "description": "Open-source voice dictation assistant.",
        "status": "ready",
    },
    # Control Center
    {
        "id": "browser_mcp_agent",
        "name": "Browser MCP Agent",
        "hub": "Control Center",
        "path": "control_center.browser_mcp_agent.app",
        "description": "Browser interaction via MCP.",
        "status": "ready",
    },
    {
        "id": "github_mcp_agent",
        "name": "GitHub MCP Agent",
        "hub": "Control Center",
        "path": "control_center.github_mcp_agent.app",
        "description": "GitHub interaction via MCP.",
        "status": "ready",
    },
    {
        "id": "notion_mcp_agent",
        "name": "Notion MCP Agent",
        "hub": "Control Center",
        "path": "control_center.notion_mcp_agent.app",
        "description": "Notion interaction via MCP.",
        "status": "ready",
    },
    {
        "id": "ai_travel_planner_mcp_agent_team",
        "name": "AI Travel Planner MCP Agent Team",
        "hub": "Control Center",
        "path": "control_center.ai_travel_planner_mcp_agent_team.app",
        "description": "Travel planning with MCP.",
        "status": "ready",
    },
    {
        "id": "multi_mcp_agent_router",
        "name": "Multi MCP Agent Router",
        "hub": "Control Center",
        "path": "control_center.multi_mcp_agent_router.app",
        "description": "Router for multiple MCP agents.",
        "status": "ready",
    },
    # Knowledge Engine
    {
        "id": "agentic_rag_embedding_gemma",
        "name": "Agentic RAG Embedding Gemma",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.agentic_rag_embedding_gemma.app",
        "description": "RAG with Gemma embeddings.",
        "status": "ready",
    },
    {
        "id": "agentic_rag_with_reasoning",
        "name": "Agentic RAG with Reasoning",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.agentic_rag_with_reasoning.app",
        "description": "RAG with reasoning capabilities.",
        "status": "ready",
    },
    {
        "id": "ai_blog_search",
        "name": "AI Blog Search",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.ai_blog_search.app",
        "description": "Search blogs with AI.",
        "status": "ready",
    },
    {
        "id": "autonomous_rag",
        "name": "Autonomous RAG",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.autonomous_rag.app",
        "description": "Autonomous retrieval-augmented generation.",
        "status": "ready",
    },
    {
        "id": "contextualai_rag_agent",
        "name": "ContextualAI RAG Agent",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.contextualai_rag_agent.app",
        "description": "RAG agent from ContextualAI.",
        "status": "ready",
    },
    {
        "id": "corrective_rag",
        "name": "Corrective RAG",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.corrective_rag.app",
        "description": "RAG with correction mechanisms.",
        "status": "ready",
    },
    {
        "id": "deepseek_local_rag_agent",
        "name": "DeepSeek Local RAG Agent",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.deepseek_local_rag_agent.app",
        "description": "Local RAG with DeepSeek.",
        "status": "ready",
    },
    {
        "id": "gemini_agentic_rag",
        "name": "Gemini Agentic RAG",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.gemini_agentic_rag.app",
        "description": "Agentic RAG with Gemini.",
        "status": "ready",
    },
    {
        "id": "hybrid_search_rag",
        "name": "Hybrid Search RAG",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.hybrid_search_rag.app",
        "description": "Hybrid search for RAG.",
        "status": "ready",
    },
    {
        "id": "llama3.1_local_rag",
        "name": "Llama3.1 Local RAG",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.llama3.1_local_rag.app",
        "description": "Local RAG with Llama3.1.",
        "status": "ready",
    },
    {
        "id": "local_hybrid_search_rag",
        "name": "Local Hybrid Search RAG",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.local_hybrid_search_rag.app",
        "description": "Local hybrid search RAG.",
        "status": "ready",
    },
    {
        "id": "local_rag_agent",
        "name": "Local RAG Agent",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.local_rag_agent.app",
        "description": "Local RAG agent.",
        "status": "ready",
    },
    {
        "id": "rag-as-a-service",
        "name": "RAG as a Service",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.rag_as_a_service.app",
        "description": "RAG provided as a service.",
        "status": "ready",
    },
    {
        "id": "rag_agent_cohere",
        "name": "RAG Agent Cohere",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.rag_agent_cohere.app",
        "description": "RAG agent with Cohere.",
        "status": "ready",
    },
    {
        "id": "rag_chain",
        "name": "RAG Chain",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.rag_chain.app",
        "description": "Chain for RAG operations.",
        "status": "ready",
    },
    {
        "id": "rag_database_routing",
        "name": "RAG Database Routing",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.rag_database_routing.app",
        "description": "Routing for RAG databases.",
        "status": "ready",
    },
    {
        "id": "vision_rag",
        "name": "Vision RAG",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.vision_rag.app",
        "description": "RAG for vision tasks.",
        "status": "ready",
    },
    {
        "id": "rag_failure_diagnostics_clinic",
        "name": "RAG Failure Diagnostics Clinic",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.rag_failure_diagnostics_clinic.app",
        "description": "Diagnostics for RAG failures.",
        "status": "ready",
    },
    {
        "id": "knowledge_graph_rag_citations",
        "name": "Knowledge Graph RAG Citations",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.knowledge_graph_rag_citations.app",
        "description": "RAG with knowledge graph citations.",
        "status": "ready",
    },
    {
        "id": "chat_with_github",
        "name": "Chat with GitHub",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.chat_with_github.app",
        "description": "Chat interface for GitHub.",
        "status": "ready",
    },
    {
        "id": "chat_with_gmail",
        "name": "Chat with Gmail",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.chat_with_gmail.app",
        "description": "Chat interface for Gmail.",
        "status": "ready",
    },
    {
        "id": "chat_with_pdf",
        "name": "Chat with PDF",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.chat_with_pdf.app",
        "description": "Chat interface for PDFs.",
        "status": "ready",
    },
    {
        "id": "chat_with_research_papers",
        "name": "Chat with Research Papers",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.chat_with_research_papers.app",
        "description": "Chat interface for research papers.",
        "status": "ready",
    },
    {
        "id": "chat_with_substack",
        "name": "Chat with Substack",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.chat_with_substack.app",
        "description": "Chat interface for Substack.",
        "status": "ready",
    },
    {
        "id": "chat_with_youtube_videos",
        "name": "Chat with YouTube Videos",
        "hub": "Knowledge Engine",
        "path": "knowledge_engine.chat_with_youtube_videos.app",
        "description": "Chat interface for YouTube videos.",
        "status": "ready",
    },
    # Builder Lab
    {
        "id": "self-improving-agent-skills",
        "name": "Self-Improving Agent Skills",
        "hub": "Builder Lab",
        "path": "builder_lab.self_improving_agent_skills.app",
        "description": "Skills for self-improving agents.",
        "status": "ready",
    },
    {
        "id": "academic-researcher",
        "name": "Academic Researcher",
        "hub": "Builder Lab",
        "path": "builder_lab.academic_researcher.app",
        "description": "Research skills for academics.",
        "status": "ready",
    },
    {
        "id": "code-reviewer",
        "name": "Code Reviewer",
        "hub": "Builder Lab",
        "path": "builder_lab.code_reviewer.app",
        "description": "Review code with AI.",
        "status": "ready",
    },
    {
        "id": "data-analyst",
        "name": "Data Analyst",
        "hub": "Builder Lab",
        "path": "builder_lab.data_analyst.app",
        "description": "Analyze data effectively.",
        "status": "ready",
    },
    {
        "id": "debugger",
        "name": "Debugger",
        "hub": "Builder Lab",
        "path": "builder_lab.debugger.app",
        "description": "Debug code and systems.",
        "status": "ready",
    },
    {
        "id": "deep-research",
        "name": "Deep Research",
        "hub": "Builder Lab",
        "path": "builder_lab.deep_research.app",
        "description": "Conduct deep research.",
        "status": "ready",
    },
    {
        "id": "fullstack-developer",
        "name": "Fullstack Developer",
        "hub": "Builder Lab",
        "path": "builder_lab.fullstack_developer.app",
        "description": "Fullstack development skills.",
        "status": "ready",
    },
    {
        "id": "python-expert",
        "name": "Python Expert",
        "hub": "Builder Lab",
        "path": "builder_lab.python_expert.app",
        "description": "Expertise in Python.",
        "status": "ready",
    },
    {
        "id": "sprint-planner",
        "name": "Sprint Planner",
        "hub": "Builder Lab",
        "path": "builder_lab.sprint_planner.app",
        "description": "Plan development sprints.",
        "status": "ready",
    },
    {
        "id": "technical-writer",
        "name": "Technical Writer",
        "hub": "Builder Lab",
        "path": "builder_lab.technical_writer.app",
        "description": "Write technical documentation.",
        "status": "ready",
    },
    {
        "id": "ai_arxiv_agent_memory",
        "name": "AI ArXiv Agent Memory",
        "hub": "Builder Lab",
        "path": "builder_lab.ai_arxiv_agent_memory.app",
        "description": "Memory for ArXiv agent.",
        "status": "ready",
    },
    {
        "id": "ai_travel_agent_memory",
        "name": "AI Travel Agent Memory",
        "hub": "Builder Lab",
        "path": "builder_lab.ai_travel_agent_memory.app",
        "description": "Memory for travel agent.",
        "status": "ready",
    },
    {
        "id": "llama3_stateful_chat",
        "name": "Llama3 Stateful Chat",
        "hub": "Builder Lab",
        "path": "builder_lab.llama3_stateful_chat.app",
        "description": "Stateful chat with Llama3.",
        "status": "ready",
    },
    {
        "id": "llm_app_personalized_memory",
        "name": "LLM App Personalized Memory",
        "hub": "Builder Lab",
        "path": "builder_lab.llm_app_personalized_memory.app",
        "description": "Personalized memory for LLM apps.",
        "status": "ready",
    },
    {
        "id": "local_chatgpt_with_memory",
        "name": "Local ChatGPT with Memory",
        "hub": "Builder Lab",
        "path": "builder_lab.local_chatgpt_with_memory.app",
        "description": "Local ChatGPT with memory.",
        "status": "ready",
    },
    {
        "id": "multi_llm_memory",
        "name": "Multi LLM Memory",
        "hub": "Builder Lab",
        "path": "builder_lab.multi_llm_memory.app",
        "description": "Memory for multiple LLMs.",
        "status": "ready",
    },
    {
        "id": "toonify_token_optimization",
        "name": "Toonify Token Optimization",
        "hub": "Builder Lab",
        "path": "builder_lab.toonify_token_optimization.app",
        "description": "Optimize tokens with Toonify.",
        "status": "ready",
    },
    {
        "id": "headroom_context_optimization",
        "name": "Headroom Context Optimization",
        "hub": "Builder Lab",
        "path": "builder_lab.headroom_context_optimization.app",
        "description": "Optimize context headroom.",
        "status": "ready",
    },
    {
        "id": "gemma3_finetuning",
        "name": "Gemma3 Finetuning",
        "hub": "Builder Lab",
        "path": "builder_lab.gemma3_finetuning.app",
        "description": "Finetune Gemma3 models.",
        "status": "ready",
    },
    {
        "id": "llama3.2_finetuning",
        "name": "Llama3.2 Finetuning",
        "hub": "Builder Lab",
        "path": "builder_lab.llama3.2_finetuning.app",
        "description": "Finetune Llama3.2 models.",
        "status": "ready",
    },
    {
        "id": "google_adk_crash_course",
        "name": "Google ADK Crash Course",
        "hub": "Builder Lab",
        "path": "builder_lab.google_adk_crash_course.app",
        "description": "Crash course on Google ADK.",
        "status": "ready",
    },
    {
        "id": "openai_sdk_crash_course",
        "name": "OpenAI SDK Crash Course",
        "hub": "Builder Lab",
        "path": "builder_lab.openai_sdk_crash_course.app",
        "description": "Crash course on OpenAI SDK.",
        "status": "ready",
    },
    {
        "id": "ai_3dpygame_r1",
        "name": "AI 3D Pygame R1",
        "hub": "Builder Lab",
        "path": "builder_lab.ai_3dpygame_r1.app",
        "description": "3D game with Pygame and AI.",
        "status": "ready",
    },
    {
        "id": "ai_chess_agent",
        "name": "AI Chess Agent",
        "hub": "Builder Lab",
        "path": "builder_lab.ai_chess_agent.app",
        "description": "AI agent for playing chess.",
        "status": "ready",
    },
    {
        "id": "ai_tic_tac_toe_agent",
        "name": "AI Tic Tac Toe Agent",
        "hub": "Builder Lab",
        "path": "builder_lab.ai_tic_tac_toe_agent.app",
        "description": "AI agent for Tic Tac Toe.",
        "status": "ready",
    },
]


def get_apps_by_hub(hub_name: str) -> List[Dict[str, str]]:
    return [app for app in APP_CATALOG if app["hub"] == hub_name]


def get_app_by_id(app_id: str) -> Optional[Dict[str, str]]:
    for app in APP_CATALOG:
        if app["id"] == app_id:
            return app
    return None